services:
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'Shuttl-Tech/ecr-push']
    volumes:
      - ".:/plugin:ro"
  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"